import type { Effect } from "./schema.js";

export enum Risk {
  SAFE = 0,
  WRITE = 1,
  NETWORK = 2,
  EXECUTE = 4,
  SECRET = 8,
  DANGEROUS = 16,
}

export interface SubCommandRule {
  command: string;
  pattern: string;
  effect: Effect;
}

export const DENY_LIST: Record<string, string[]> = {
  bash: [
    "rm -rf /",
    "rm -rf /*",
    "sudo *",
    "shutdown *",
    "reboot *",
    "mkfs *",
    "dd if=*",
    "mkswap *",
    "swapoff *",
    "swapon *",
    ":(){ :|:& };:*",
  ],
};

export const COMMAND_RISKS: Record<string, Risk> = {
  ls: Risk.SAFE,
  cat: Risk.SAFE,
  head: Risk.SAFE,
  tail: Risk.SAFE,
  grep: Risk.SAFE,
  find: Risk.SAFE,
  tree: Risk.SAFE,
  stat: Risk.SAFE,
  file: Risk.SAFE,
  du: Risk.SAFE,
  df: Risk.SAFE,
  ps: Risk.SAFE,
  pwd: Risk.SAFE,
  whoami: Risk.SAFE,
  date: Risk.SAFE,
  which: Risk.SAFE,
  realpath: Risk.SAFE,
  dirname: Risk.SAFE,
  basename: Risk.SAFE,
  wc: Risk.SAFE,
  sort: Risk.SAFE,
  uniq: Risk.SAFE,
  echo: Risk.SAFE,
  printf: Risk.SAFE,
  true: Risk.SAFE,
  false: Risk.SAFE,
  yes: Risk.SAFE,
  dir: Risk.SAFE,
  type: Risk.SAFE,
  where: Risk.SAFE,
  fc: Risk.SAFE,
  more: Risk.SAFE,

  rm: Risk.WRITE,
  del: Risk.WRITE,
  erase: Risk.WRITE,
  rd: Risk.WRITE,
  rmdir: Risk.WRITE,
  mv: Risk.WRITE,
  cp: Risk.WRITE,
  chmod: Risk.WRITE,
  chown: Risk.WRITE,
  touch: Risk.WRITE,
  mkdir: Risk.WRITE,
  ln: Risk.WRITE,
  install: Risk.WRITE,
  truncate: Risk.WRITE,
  shred: Risk.WRITE,

  curl: Risk.NETWORK,
  wget: Risk.NETWORK,
  scp: Risk.NETWORK,
  ssh: Risk.NETWORK,
  rsync: Risk.NETWORK,
  nc: Risk.NETWORK,
  telnet: Risk.NETWORK,
  ping: Risk.NETWORK,
  traceroute: Risk.NETWORK,

  node: Risk.EXECUTE,
  python: Risk.EXECUTE,
  python3: Risk.EXECUTE,
  bun: Risk.EXECUTE,
  deno: Risk.EXECUTE,
  "ts-node": Risk.EXECUTE,
  tsx: Risk.EXECUTE,
  bash: Risk.EXECUTE,
  sh: Risk.EXECUTE,
  zsh: Risk.EXECUTE,
  fish: Risk.EXECUTE,
  pwsh: Risk.EXECUTE,
  cmd: Risk.EXECUTE,
  exec: Risk.EXECUTE,

  env: Risk.SECRET,
  printenv: Risk.SECRET,
  set: Risk.SECRET,

  sudo: Risk.DANGEROUS,
  su: Risk.DANGEROUS,
  passwd: Risk.DANGEROUS,
  useradd: Risk.DANGEROUS,
  userdel: Risk.DANGEROUS,
  usermod: Risk.DANGEROUS,
  groupadd: Risk.DANGEROUS,
  groupdel: Risk.DANGEROUS,
};

export const SUB_COMMAND_RULES: SubCommandRule[] = [
  { command: "git", pattern: "status *", effect: "allow" },
  { command: "git", pattern: "log *", effect: "allow" },
  { command: "git", pattern: "diff *", effect: "allow" },
  { command: "git", pattern: "show *", effect: "allow" },
  { command: "git", pattern: "branch *", effect: "allow" },
  { command: "git", pattern: "remote *", effect: "allow" },
  { command: "git", pattern: "tag *", effect: "allow" },
  { command: "git", pattern: "fetch *", effect: "allow" },
  { command: "git", pattern: "rev-parse *", effect: "allow" },
  { command: "git", pattern: "describe *", effect: "allow" },
  { command: "git", pattern: "blame *", effect: "allow" },
  { command: "git", pattern: "shortlog *", effect: "allow" },
  { command: "git", pattern: "reflog *", effect: "allow" },
  { command: "git", pattern: "ls-files *", effect: "allow" },
  { command: "git", pattern: "ls-remote *", effect: "allow" },

  { command: "git", pattern: "push *", effect: "ask" },
  { command: "git", pattern: "pull *", effect: "ask" },
  { command: "git", pattern: "reset *", effect: "ask" },
  { command: "git", pattern: "clean *", effect: "ask" },
  { command: "git", pattern: "checkout *", effect: "ask" },
  { command: "git", pattern: "switch *", effect: "ask" },
  { command: "git", pattern: "commit *", effect: "ask" },
  { command: "git", pattern: "merge *", effect: "ask" },
  { command: "git", pattern: "rebase *", effect: "ask" },
  { command: "git", pattern: "config *", effect: "ask" },
  { command: "git", pattern: "stash *", effect: "ask" },
  { command: "git", pattern: "add *", effect: "ask" },
  { command: "git", pattern: "rm *", effect: "ask" },
  { command: "git", pattern: "mv *", effect: "ask" },
  { command: "git", pattern: "cherry-pick *", effect: "ask" },
  { command: "git", pattern: "revert *", effect: "ask" },
  { command: "git", pattern: "bisect *", effect: "ask" },
  { command: "git", pattern: "worktree *", effect: "ask" },
  { command: "git", pattern: "submodule *", effect: "ask" },

  { command: "npm", pattern: "ls *", effect: "allow" },
  { command: "npm", pattern: "list *", effect: "allow" },
  { command: "npm", pattern: "view *", effect: "allow" },
  { command: "npm", pattern: "info *", effect: "allow" },
  { command: "npm", pattern: "outdated *", effect: "allow" },
  { command: "npm", pattern: "version *", effect: "allow" },
  { command: "npm", pattern: "ping *", effect: "allow" },
  { command: "npm", pattern: "whoami *", effect: "allow" },
  { command: "npm", pattern: "test *", effect: "allow" },

  { command: "npm", pattern: "install *", effect: "ask" },
  { command: "npm", pattern: "i *", effect: "ask" },
  { command: "npm", pattern: "uninstall *", effect: "ask" },
  { command: "npm", pattern: "publish *", effect: "ask" },
  { command: "npm", pattern: "config *", effect: "ask" },
  { command: "npm", pattern: "cache *", effect: "ask" },
  { command: "npm", pattern: "link *", effect: "ask" },
  { command: "npm", pattern: "unlink *", effect: "ask" },
  { command: "npm", pattern: "run *", effect: "ask" },
  { command: "npm", pattern: "exec *", effect: "ask" },
  { command: "npm", pattern: "init *", effect: "ask" },
  { command: "npm", pattern: "audit *", effect: "ask" },
  { command: "npm", pattern: "fix *", effect: "ask" },
  { command: "npm", pattern: "dedupe *", effect: "ask" },
  { command: "npm", pattern: "prune *", effect: "ask" },
  { command: "npm", pattern: "rebuild *", effect: "ask" },

  { command: "npx", pattern: "*", effect: "ask" },

  { command: "yarn", pattern: "list *", effect: "allow" },
  { command: "yarn", pattern: "info *", effect: "allow" },
  { command: "yarn", pattern: "why *", effect: "allow" },
  { command: "yarn", pattern: "test *", effect: "allow" },
  { command: "yarn", pattern: "*", effect: "ask" },

  { command: "pnpm", pattern: "list *", effect: "allow" },
  { command: "pnpm", pattern: "info *", effect: "allow" },
  { command: "pnpm", pattern: "why *", effect: "allow" },
  { command: "pnpm", pattern: "test *", effect: "allow" },
  { command: "pnpm", pattern: "*", effect: "ask" },

  { command: "bun", pattern: "test *", effect: "allow" },
  { command: "bun", pattern: "*", effect: "ask" },

  { command: "pip", pattern: "list *", effect: "allow" },
  { command: "pip", pattern: "show *", effect: "allow" },
  { command: "pip", pattern: "freeze *", effect: "allow" },
  { command: "pip", pattern: "check *", effect: "allow" },
  { command: "pip", pattern: "search *", effect: "allow" },
  { command: "pip", pattern: "*", effect: "ask" },

  { command: "pip3", pattern: "list *", effect: "allow" },
  { command: "pip3", pattern: "show *", effect: "allow" },
  { command: "pip3", pattern: "freeze *", effect: "allow" },
  { command: "pip3", pattern: "check *", effect: "allow" },
  { command: "pip3", pattern: "search *", effect: "allow" },
  { command: "pip3", pattern: "*", effect: "ask" },

  { command: "cargo", pattern: "check *", effect: "allow" },
  { command: "cargo", pattern: "build *", effect: "allow" },
  { command: "cargo", pattern: "test *", effect: "allow" },
  { command: "cargo", pattern: "clippy *", effect: "allow" },
  { command: "cargo", pattern: "doc *", effect: "allow" },
  { command: "cargo", pattern: "fmt *", effect: "allow" },
  { command: "cargo", pattern: "tree *", effect: "allow" },
  { command: "cargo", pattern: "metadata *", effect: "allow" },
  { command: "cargo", pattern: "locate-project *", effect: "allow" },
  { command: "cargo", pattern: "manifest-path *", effect: "allow" },
  { command: "cargo", pattern: "version *", effect: "allow" },

  { command: "cargo", pattern: "publish *", effect: "ask" },
  { command: "cargo", pattern: "install *", effect: "ask" },
  { command: "cargo", pattern: "uninstall *", effect: "ask" },
  { command: "cargo", pattern: "clean *", effect: "ask" },
  { command: "cargo", pattern: "run *", effect: "ask" },
  { command: "cargo", pattern: "bench *", effect: "ask" },
  { command: "cargo", pattern: "update *", effect: "ask" },
  { command: "cargo", pattern: "add *", effect: "ask" },
  { command: "cargo", pattern: "remove *", effect: "ask" },
  { command: "cargo", pattern: "generate-lockfile *", effect: "ask" },
  { command: "cargo", pattern: "vendor *", effect: "ask" },
  { command: "cargo", pattern: "package *", effect: "ask" },
  { command: "cargo", pattern: "login *", effect: "ask" },
  { command: "cargo", pattern: "owner *", effect: "ask" },
  { command: "cargo", pattern: "yank *", effect: "ask" },

  { command: "go", pattern: "build *", effect: "allow" },
  { command: "go", pattern: "test *", effect: "allow" },
  { command: "go", pattern: "vet *", effect: "allow" },
  { command: "go", pattern: "fmt *", effect: "allow" },
  { command: "go", pattern: "list *", effect: "allow" },
  { command: "go", pattern: "doc *", effect: "allow" },
  { command: "go", pattern: "env *", effect: "allow" },
  { command: "go", pattern: "version *", effect: "allow" },
  { command: "go", pattern: "mod *", effect: "allow" },

  { command: "go", pattern: "install *", effect: "ask" },
  { command: "go", pattern: "run *", effect: "ask" },
  { command: "go", pattern: "generate *", effect: "ask" },
  { command: "go", pattern: "clean *", effect: "ask" },
  { command: "go", pattern: "get *", effect: "ask" },
  { command: "go", pattern: "tool *", effect: "ask" },

  { command: "make", pattern: "test *", effect: "allow" },
  { command: "make", pattern: "build *", effect: "allow" },
  { command: "make", pattern: "check *", effect: "allow" },
  { command: "make", pattern: "lint *", effect: "allow" },
  { command: "make", pattern: "format *", effect: "allow" },
  { command: "make", pattern: "dry-run *", effect: "allow" },

  { command: "make", pattern: "install *", effect: "ask" },
  { command: "make", pattern: "clean *", effect: "ask" },
  { command: "make", pattern: "uninstall *", effect: "ask" },
  { command: "make", pattern: "deploy *", effect: "ask" },
  { command: "make", pattern: "publish *", effect: "ask" },
  { command: "make", pattern: "*", effect: "ask" },

  { command: "jest", pattern: "*", effect: "allow" },
  { command: "vitest", pattern: "*", effect: "allow" },
  { command: "pytest", pattern: "*", effect: "allow" },
  { command: "mocha", pattern: "*", effect: "allow" },
  { command: "jasmine", pattern: "*", effect: "allow" },
  { command: "ava", pattern: "*", effect: "allow" },
  { command: "tap", pattern: "*", effect: "allow" },

  { command: "eslint", pattern: "*", effect: "allow" },
  { command: "prettier", pattern: "*", effect: "allow" },
  { command: "biome", pattern: "*", effect: "allow" },
  { command: "ruff", pattern: "*", effect: "allow" },
  { command: "black", pattern: "*", effect: "allow" },
  { command: "flake8", pattern: "*", effect: "allow" },
  { command: "mypy", pattern: "*", effect: "allow" },
  { command: "pylint", pattern: "*", effect: "allow" },
  { command: "tsc", pattern: "*", effect: "allow" },

  { command: "git", pattern: "*", effect: "ask" },
  { command: "npm", pattern: "*", effect: "ask" },
  { command: "cargo", pattern: "*", effect: "ask" },
  { command: "go", pattern: "*", effect: "ask" },
];

export const SENSITIVE_READ_PATTERNS: string[] = [
  "*.pem",
  "*.key",
  "*.p12",
  "*.crt",
  "*.cer",
  "*.ovpn",
  "*.jks",
  "*.keystore",
  "*.pfx",
  "id_rsa",
  "id_ed25519",
  "id_dsa",
  "id_ecdsa",
  "*.kdbx",
  "*.secret",
  "*.token",
  "*.credentials",
  "*.sqlite",
  "*.sqlite3",
  "*.db",
  "*.env",
  "*.env.*",
  ".env.*",
  ".env",
  "~/.ssh/*",
  ".ssh/*",
  "~/.aws/*",
  ".aws/*",
  "~/.azure/*",
  ".azure/*",
  "~/.gcp/*",
  ".gcp/*",
  "~/.kube/*",
  ".kube/*",
  "~/.docker/*",
  ".docker/*",
  "~/.gnupg/*",
  ".gnupg/*",
  "~/.config/gcloud/*",
  "~/.config/gh/*",
  ".netrc",
  "~/.netrc",
  ".npmrc",
  "~/.npmrc",
  ".pypirc",
  "~/.pypirc",
];
